### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (593,464,2) (592,464,2)

### ISSUE THREAD

**Issue by shangjaven** [ZiwenZhuang/parkour#35]
Hello.
I am running `python legged_gym/scripts/play.py --task a1_jump --load_run Apr06_01-05-16_Skills_jump_from_Apr05_10-43-00_WalkingBase _pEnergySubsteps2e-5_aScale0.5` ran into a similar problem to [#11.](https://github.com/ZiwenZhuang/parkour/issues/11)
After reading your reply I tried to change the `track_block_length` in `a1_jump_config.py` under `parkour/legged_gym/envs/a1` from 1.6 to 2 and `n_obstacles_per_track` to 3. In addition, I also changed the `parkour/legged_gym/legged_gym/utils/terrain/barrier_track.py` also to 2 and 3. But it doesn't work for me, it still reports the same error. Looking forward to your answer!

```
(corl) bld@bld-System-Product-Name:~/corl/parkour/legged_gym$ python legged_gym/scripts/play.py --task a1_jump --load_run Apr06_01-05-16_Skills_jump_from_Apr05_10-43-00_WalkingBase_pEnergySubsteps2e-5_aScale0.5
Importing module 'gym_38' (/home/bld/corl/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/bld/corl/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.13.0
Device count 1
/home/bld/corl/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/bld/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
Emitting ninja build file /home/bld/.cache/torch_extensions/py38_cu116/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Setting seed: 1
Using LeggedRobotField.__init__, num_obs and num_privileged_obs will be computed instead of assigned.
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
Traceback (most recent call last):
  File "legged_gym/scripts/play.py", line 340, in <module>
    play(args)
  File "/home/bld/anaconda3/envs/corl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "legged_gym/scripts/play.py", line 164, in play
    env, _ = task_registry.make_env(name=args.task, args=args, env_cfg=env_cfg)
  File "/home/bld/corl/parkour/legged_gym/legged_gym/utils/task_registry.py", line 99, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/bld/corl/parkour/legged_gym/legged_gym/envs/base/legged_robot_field.py", line 20, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/bld/corl/parkour/legged_gym/legged_gym/envs/base/legged_robot.py", line 72, in __init__
    super().__init__(self.cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/bld/corl/parkour/legged_gym/legged_gym/envs/base/base_task.py", line 84, in __init__
    self.create_sim()
  File "/home/bld/corl/parkour/legged_gym/legged_gym/envs/base/legged_robot.py", line 238, in create_sim
    self._create_terrain()
  File "/home/bld/corl/parkour/legged_gym/legged_gym/envs/base/legged_robot_field.py", line 632, in _create_terrain
    self.terrain.add_terrain_to_sim(self.gym, self.sim, self.device)
  File "/home/bld/corl/parkour/legged_gym/legged_gym/utils/terrain/barrier_track.py", line 600, in add_terrain_to_sim
    self.build_heightfield_raw()
  File "/home/bld/corl/parkour/legged_gym/legged_gym/utils/terrain/barrier_track.py", line 444, in build_heightfield_raw
    heightfield_noise = TerrainPerlin.generate_fractal_noise_2d(
  File "/home/bld/corl/parkour/legged_gym/legged_gym/utils/terrain/perlin.py", line 69, in generate_fractal_noise_2d
    noise += amplitude * TerrainPerlin.generate_perlin_noise_2d((xSamples, ySamples), (xScale, yScale)) * zScale
  File "/home/bld/corl/parkour/legged_gym/legged_gym/utils/terrain/perlin.py", line 50, in generate_perlin_noise_2d
    n00 = np.sum(grid * g00, 2)
ValueError: operands could not be broadcast together with shapes (593,464,2) (592,464,2) 
```

**Comment by shangjaven** [comment]
I changed `env_cfg.terrain.BarrierTrack_kwargs["n_obstacles_per_track" ] = 2` to `env_cfg.terrain.BarrierTrack_kwargs["n_obstacles_per_track"] = 3` solved my problem.
