### ISSUE TITLE
'LeggedRobot' object has no attribute 'torque_exceed_count_envstep'

### ISSUE THREAD

**Issue by CoderWangcai** [ZiwenZhuang/parkour#61]
Thank the author for providing such a great project. I encountered an error while visualizing and sincerely request your help.

```
python legged_gym/scripts/play.py --task go2 --load_run /root/code/parkour/legged_gym/logs/rough_go2/Oct08
_00-28-39_Go2Rough_pEnergy-2e-05_pDofErr-1e-02_pDofErrN-1e+00_pStand-2e+00_noResume
```

```
Importing module 'gym_38' (/root/data/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /root/data/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 1
/root/data/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Setting seed: 1
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
Terrain heightsamples shape:  (320, 320)
Terrain heightsamples stat:  0.005 0.075 0.0411615234375 0.011154892425428772 0.04
/root/miniconda3/envs/parkour/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Total number of volume estimation points for each robot is: 3034
terrain_levels: tensor(0., device='cuda:0') tensor(0., device='cuda:0') tensor(0., device='cuda:0')
'train_cfg' provided -> Ignoring 'name=go2'
Actor MLP: Sequential(
  (0): Linear(in_features=256, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=12, bias=True)
)
Critic MLP: Sequential(
  (0): Linear(in_features=256, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=1, bias=True)
)
Actor RNN: Memory(
  (rnn): GRU(80, 256)
)
Critic RNN: Memory(
  (rnn): GRU(80, 256)
)
Loading load_run as absolute path: /root/code/parkour/legged_gym/logs/rough_go2/Oct08_00-28-39_Go2Rough_pEnergy-2e-05_pDofErr-1e-02_pDofErrN-1e+00_pStand-2e+00_noResume
Loading model from: /root/code/parkour/legged_gym/logs/rough_go2/Oct08_00-28-39_Go2Rough_pEnergy-2e-05_pDofErr-1e-02_pDofErrN-1e+00_pStand-2e+00_noResume/model_2000.pt
motor_strength: [0.8989605903625488, 0.9956339001655579, 1.0311477184295654, 1.175426721572876, 1.0864994525909424, 1.1028919219970703, 0.927577555179596, 0.8704398274421692, 1.0588566064834595, 1.187929391860962, 1.1548715829849243, 0.9926556944847107]
torque_limits: tensor([23.7000, 23.7000, 45.4300, 23.7000, 23.7000, 45.4300, 23.7000, 23.7000,
        45.4300, 23.7000, 23.7000, 45.4300], device='cuda:0')
Traceback (most recent call last):
  File "legged_gym/scripts/play.py", line 510, in <module>
    play(args)
  File "/root/miniconda3/envs/parkour/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "legged_gym/scripts/play.py", line 408, in play
    if env.torque_exceed_count_envstep[robot_index].any():
AttributeError: 'LeggedRobot' object has no attribute 'torque_exceed_count_envstep'
```

**Comment by ZiwenZhuang** [comment]
Hi,

Just remove the if block in `play.py`. They are for the data visualization.

We will update the script later.
