### ISSUE TITLE
a1_field was not registered

### ISSUE THREAD

**Issue by CoderWangcai** [ZiwenZhuang/parkour#67]
When I run `python legged_gym/scripts/train.py --headless --task a1_field`, I encounter the following error:
```
Importing module 'gym_38' (/root/data/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /root/data/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 2
/root/data/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 51, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 45, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/root/code/parkour/legged_gym/legged_gym/utils/task_registry.py", line 89, in make_env
    raise ValueError(f"Task with name: {name} was not registered")
ValueError: Task with name: a1_field was not registered
```

**Comment by Yan-shiyang** [comment]
I tried too.
The A1 env config and training cfg exist, but the mesh_type trimesh and plane don't exist in the opensource code. So after registering a1_filed, the code still can't run, and will get "Not implemented for mesh_type other than None" error.

**Comment by 1242713693** [comment]
Excuse me, have you solved this problem?

**Comment by hamidh1** [comment]
> I tried too. The A1 env config and training cfg exist, but the mesh_type trimesh and plane don't exist in the opensource code. So after registering a1_filed, the code still can't run, and will get "Not implemented for mesh_type other than None" error.

@Yan-shiyang  Have you resolved this issue?
